version: '3'
services:
    oracle:
        image: sath89/oracle-12c
        restart: always
        ports:
            - 8080:8080
            - 1521:1521
    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8083