version: '3'
services:
    sqlserver:
        image: microsoft/mssql-server-linux
        restart: always
        ports:
            - ${SQLSERVER_PORT}:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${SQLSERVER_PASSWORD}
    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8083